### ISSUE TITLE
Linked Context URL missing concepts

### ISSUE THREAD

**Issue by piripopero** [smart-data-models/dataModel.Battery#5]
We are trying some examples with orionld linking the context to  "https://schema.lab.fiware.org/ld/context" and         "https://smartdatamodels.org/context.jsonld" but none of both resolve most of the concepts of StorageBatteryMeasurement (i.e. measurementInterval, openCircuitVoltage, stateOfHealth, stateOfCharge...)

Is there more updated contexts to link?

**Comment by albertoabellagarcia** [comment]
It will be soon in the context, however soon is something that depends on a complex script that is in development. regarding schema.lab is not going to be updated, however, maybe we could fix it manually for the terms you need. please could you reply with the terms you need to resolve?

**Comment by albertoabellagarcia** [comment]
Now every subject has a local @context at root context.jsonld
See the example in the battery subject [link](https://github.com/smart-data-models/dataModel.Battery/blob/master/context.jsonld) 
Additionally, there will be a mapping with external ontologies you can create through a script to be released very soon.
See [this post](https://smartdatamodels.org/index.php/local-context-available-in-all-subjects/) explaining the resources related to the context 

Note: measurementInterval is an attribute not available in the schema. Is it missing? the others are available. 
Best
