### ISSUE TITLE
Adding URI for class Battery

### ISSUE THREAD

**Issue by EmidioStani** [smart-data-models/dataModel.Battery#6]
Hello,

in the local context there are the URI of the properties but not the classes per se, for example "Battery" itself, which appears in the example: https://github.com/smart-data-models/dataModel.Battery/blob/master/Battery/examples/example.jsonld.

I guess it should appear in https://smart-data-models.github.io/data-models/context.jsonld like for the "Point" class.

Thanks for looking into,

Emidio

**Comment by albertoabellagarcia** [comment]
You are right. We are in the progress of complementing the context.jsonld with them.
I am not closing this issue till we implement it.

**Comment by albertoabellagarcia** [comment]
We have just launched the script for including the long IRI for entity names. It will take some minutes for all the data models. These IRI, contrary to the attributes, will not take you to an actual web page. We'll try to solve this soon as well.
